// examples/vue-code-spliting/src/App.vue
<template>
  <section>
    <div>app</div>
    <loading></loading>
  </section>
</template>

<script>
import Loading from "./Loading"
import Error from "./Error"

export default {
  components: {
    loading: () => ({
      component: (() => {
        return new Promise(resolve => {
          setTimeout(() => {
            import("./List").then(resolve)
          }, 5000)
        })
      })(),
      loading: Loading,
      error: Error
    })
  }
}
</script>

// examples/react-code-spliting/src/Containers/App.jsx
import React from 'react'
import Loading from './Loading'
import Error from './Error'

const Suspense = React.Suspense

const List = React.lazy(
  () => new Promise((resolve, reject) => {
    setTimeout(() => {
      /* eslint-disable */
      import('./List').then(() => {
        reject()
      })
    }, 5000)
  })
)
export default () => (
  <div>
    <div>app</div>
    <Error>
      <Suspense fallback={<Loading />}>
        <List />
      </Suspense>
    </Error>
  </div>
)
